language: node_js

node_js:
  - '8.8.1'

before_install:
 - npm install -g angular-cli protractor
install:
 - npm install
 - webdriver-manager update
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 5
 - webdriver-manager start --detach --seleniumPort=4444 &
 - sleep 30
script:
 - protractor

notifications:
  email: false
